### ISSUE TITLE
use grove-LCD on GrovePi  

### ISSUE THREAD

**Issue by jackswei** [dotnet/iot#1101]
want use grove-LCD display text in GrovePi  

**Describe the bug**

var i2cLcdDevice = I2cDevice.Create(new I2cConnectionSettings(busId: 1, deviceAddress: 0x3E));
var i2cRgbDevice = I2cDevice.Create(new I2cConnectionSettings(busId: 1, deviceAddress: 0x62));
using (var lcd = new LcdRgb1602(i2cLcdDevice, i2cRgbDevice))
{
    lcd.Write("Hello World!");
    lcd.SetBacklightColor(Color.Azure);
}
**can't find LcdRgb1602 class 

**Steps to reproduce**

```csharp
// put sample code here
 Console.WriteLine("Hello GrovePi!");
            PinValue relay = PinValue.Low;
                Console.WriteLine(GrovePi.DefaultI2cAddress);
            I2cConnectionSettings i2CConnectionSettings = new I2cConnectionSettings(1, GrovePi.DefaultI2cAddress);
            _grovePi = new GrovePi(I2cDevice.Create(i2CConnectionSettings));
            Console.WriteLine($"Manufacturer :{_grovePi.GrovePiInfo.Manufacturer}");
            Console.WriteLine($"Board: {_grovePi.GrovePiInfo.Board}");
            Console.WriteLine($"Firmware version: {_grovePi.GrovePiInfo.SoftwareVersion}");
            // Specific example to show how to read directly a pin without a high level class
      
            _grovePi.PinMode(GrovePort.DigitalPin7, PinMode.Output);
            _grovePi.PinMode(GrovePort.DigitalPin8, PinMode.Output);

            OneWrieList = OneWireThermometerDevice.EnumerateDevices().ToList();
            var i2cLcdDevice = I2cDevice.Create(new I2cConnectionSettings(busId: 1, deviceAddress: 0x3E));
            var i2cRgbDevice = I2cDevice.Create(new I2cConnectionSettings(busId: 1, deviceAddress: 0x62));
            using (var lcd = new LcdRgb1602(i2cLcdDevice, i2cRgbDevice))
            {
                lcd.Write("Hello World!");
                lcd.SetBacklightColor(Color.Azure);
            }




Add following information:
Iot.Device.Bindings 1.1.0-prerelease.20153.1
System.Device.Gpio 1.1.0-prerelease.20153.1

**Comment by jackswei** [comment]
Grove-LCD RGB Backlight V4.0
i use 
var i2cLcdDevice = I2cDevice.Create(new I2cConnectionSettings(busId: 1, deviceAddress: 0x3E));
            var i2cRgbDevice = I2cDevice.Create(new I2cConnectionSettings(busId: 1, deviceAddress: 0x62));
            using (var lcd = new Lcd1602(i2cLcdDevice))
            {
                lcd.Write("Hello World!");
               // lcd.SetBacklightColor(Color.Azure);
            }
error show 
Unhandled exception. System.IO.IOException: Error 121 performing I2C data transfer.
   at System.Device.I2c.UnixI2cDevice.ReadWriteInterfaceTransfer(Byte* writeBuffer, Byte* readBuffer, Int32 writeBufferLength, Int32 readBufferLength)
   at System.Device.I2c.UnixI2cDevice.Transfer(Byte* writeBuffer, Byte* readBuffer, Int32 writeBufferLength, Int32 readBufferLength)
   at System.Device.I2c.UnixI2cDevice.Write(ReadOnlySpan`1 value)
   at Iot.Device.CharacterLcd.LcdInterface.I2c.SendCommands(ReadOnlySpan`1 commands)
   at Iot.Device.CharacterLcd.Hd44780.SendCommands(ReadOnlySpan`1 commands)
   at Iot.Device.CharacterLcd.Hd44780.Initialize(Int32 rows)
   at Iot.Device.CharacterLcd.Hd44780..ctor(Size size, LcdInterface lcdInterface)
   at Iot.Device.CharacterLcd.LcdRgb..ctor(Size size, I2cDevice lcdDevice, I2cDevice rgbDevice)
   at rpitest.Program.Main(String[] args) in /home/pi/rpitest/Program.cs:line 53

**Comment by jackswei** [comment]
i find Grove-LCD RGB Backlight V4.0 on GrovePi + i2c
sudo i2cdetect -y 1
it can't find  Grove-LCD RGB Backlight V4.0

**Comment by jackswei** [comment]
I FIND GrovePi+ can't scan i2c devices
