### ISSUE TITLE
CI is unhealthy

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#1156]
CI keeps on failing with random errors:

<details>
<summary>Windows (click to expand)</summary>

```
xUnit.net Console Runner v2.4.1 (32-bit .NET Core 4.6.27617.05)
  Discovering: System.Device.Gpio.Tests
  Discovered:  System.Device.Gpio.Tests
  Starting:    System.Device.Gpio.Tests
    System.Device.Gpio.Tests.ProtocolsTests.I2C_Bme280CanRead [STARTING]
    System.Device.Gpio.Tests.ProtocolsTests.I2C_Bme280CanRead [FAIL]
      System.IO.FileNotFoundException : The system cannot find the file specified.
      
      Slave address was not acknowledged.
      Stack Trace:
           at Windows.Devices.I2c.I2cDevice.Write(Byte[] buffer)
        /_/src/System.Device.Gpio/System/Device/I2c/Devices/Windows10I2cDevice.cs(85,0): at System.Device.I2c.Windows10I2cDevice.WriteByte(Byte value)
        /_/src/devices/Bmxx80/Bmxx80Base.cs(79,0): at Iot.Device.Bmxx80.Bmxx80Base..ctor(Byte deviceId, I2cDevice i2cDevice)
        /_/src/devices/Bmxx80/Bmx280Base.cs(47,0): at Iot.Device.Bmxx80.Bmx280Base..ctor(Byte deviceId, I2cDevice i2cDevice)
        /_/src/devices/Bmxx80/Bme280.cs(35,0): at Iot.Device.Bmxx80.Bme280..ctor(I2cDevice i2cDevice)
        /_/src/System.Device.Gpio.Tests/SetupHelpers.cs(56,0): at System.Device.Gpio.Tests.SetupHelpers.CreateBme280()
        /_/src/System.Device.Gpio.Tests/ProtocolTests.cs(55,0): at System.Device.Gpio.Tests.ProtocolsTests.I2C_Bme280CanRead()
    System.Device.Gpio.Tests.ProtocolsTests.I2C_Bme280CanRead [FINISHED] Time: 0.3997995s
    System.Device.Gpio.Tests.ProtocolsTests.SPI_Mcp3008CanRead [STARTING]
    System.Device.Gpio.Tests.ProtocolsTests.SPI_Mcp3008CanRead [FAIL]
      Assert.InRange() Failure
      Range:  (1018 - 1023)
      Actual: 0
      Stack Trace:
        /_/src/System.Device.Gpio.Tests/ProtocolTests.cs(41,0): at System.Device.Gpio.Tests.ProtocolsTests.SPI_Mcp3008CanRead()
    System.Device.Gpio.Tests.ProtocolsTests.SPI_Mcp3008CanRead [FINISHED] Time: 0.1405313s
    System.Device.Gpio.Tests.Mcp3008Tests.InvalidChannel_Throws [STARTING]
    System.Device.Gpio.Tests.Mcp3008Tests.InvalidChannel_Throws [FINISHED] Time: 0.0850236s
    System.Device.Gpio.Tests.Mcp3008Tests.DoubleDispose_DoesNotThrow [STARTING]
    System.Device.Gpio.Tests.Mcp3008Tests.DoubleDispose_DoesNotThrow [FINISHED] Time: 0.0531657s
    System.Device.Gpio.Tests.Mcp3008Tests.NullSpiDevice_Throws [STARTING]
    System.Device.Gpio.Tests.Mcp3008Tests.NullSpiDevice_Throws [FINISHED] Time: 0.0041633s
    System.Device.Gpio.Tests.WindowsDriverTests.ThrowsIfWaitingOnClosedPin [STARTING]
    System.Device.Gpio.Tests.WindowsDriverTests.ThrowsIfWaitingOnClosedPin [FINISHED] Time: 0.0415191s
    System.Device.Gpio.Tests.WindowsDriverTests.AddCallbackRemoveAllCallbackTest [STARTING]
    System.Device.Gpio.Tests.WindowsDriverTests.AddCallbackRemoveAllCallbackTest [FAIL]
      System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
      Expected: 1
      Actual:   0) (Assert.Equal() Failure
      Expected: 1
      Actual:   0) (Assert.Equal() Failure
      Expected: 1
      Actual:   0) (Assert.Equal() Failure
      Expected: 1
      Actual:   0) (Assert.Equal() Failure
      Expected: 1
      Actual:   0)
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   0
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   0
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   0
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   0
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   0
      Stack Trace:
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(46,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(284,0): at System.Device.Gpio.Tests.GpioControllerTestBase.AddCallbackRemoveAllCallbackTest()
        ----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(311,0): at System.Device.Gpio.Tests.GpioControllerTestBase.<>c__DisplayClass19_0.<AddCallbackRemoveAllCallbackTest>b__0()
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(38,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #2 (Xunit.Sdk.EqualException) -----
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(311,0): at System.Device.Gpio.Tests.GpioControllerTestBase.<>c__DisplayClass19_0.<AddCallbackRemoveAllCallbackTest>b__0()
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(38,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #3 (Xunit.Sdk.EqualException) -----
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(311,0): at System.Device.Gpio.Tests.GpioControllerTestBase.<>c__DisplayClass19_0.<AddCallbackRemoveAllCallbackTest>b__0()
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(38,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #4 (Xunit.Sdk.EqualException) -----
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(311,0): at System.Device.Gpio.Tests.GpioControllerTestBase.<>c__DisplayClass19_0.<AddCallbackRemoveAllCallbackTest>b__0()
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(38,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #5 (Xunit.Sdk.EqualException) -----
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(311,0): at System.Device.Gpio.Tests.GpioControllerTestBase.<>c__DisplayClass19_0.<AddCallbackRemoveAllCallbackTest>b__0()
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(38,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
    System.Device.Gpio.Tests.WindowsDriverTests.AddCallbackRemoveAllCallbackTest [FINISHED] Time: 16.2922514s
    System.Device.Gpio.Tests.WindowsDriverTests.WaitForEventRisingEdgeTest [STARTING]
```

</details>

<details>
<summary>Linux (click to expand)</summary>

```
    System.Device.Gpio.Tests.SysFsDriverTests.FastInterruptHandling [FAIL]
      Expected at least 99, got only 0
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(490,0): at System.Device.Gpio.Tests.GpioControllerTestBase.FastInterruptHandling()
```

</details>

ref: https://github.com/dotnet/iot/pull/1154

**Comment by Ellerbach** [comment]
[Triage] CI fixed.
