### ISSUE TITLE
System.Device.Gpio.Tests.WindowsDriverTests.AddCallbackRemoveAllCallbackTest failing on CI

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#1194]
Note: Test will be disabled and needs to be re-enabled as part of this bug, search for number of this bug in the repo

```
    System.Device.Gpio.Tests.WindowsDriverTests.ThrowsIfWaitingOnClosedPin [STARTING]
    System.Device.Gpio.Tests.WindowsDriverTests.ThrowsIfWaitingOnClosedPin [FINISHED] Time: 0.2076317s
    System.Device.Gpio.Tests.WindowsDriverTests.AddCallbackRemoveAllCallbackTest [STARTING]
    System.Device.Gpio.Tests.WindowsDriverTests.AddCallbackRemoveAllCallbackTest [FAIL]
      System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
      Expected: 1
      Actual:   0) (Assert.Equal() Failure
      Expected: 1
      Actual:   0) (Assert.Equal() Failure
      Expected: 1
      Actual:   0) (Assert.Equal() Failure
      Expected: 1
      Actual:   0) (Assert.Equal() Failure
      Expected: 1
      Actual:   0)
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   0
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   0
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   0
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   0
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   0
      Stack Trace:
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(46,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(284,0): at System.Device.Gpio.Tests.GpioControllerTestBase.AddCallbackRemoveAllCallbackTest()
        ----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(311,0): at System.Device.Gpio.Tests.GpioControllerTestBase.<>c__DisplayClass19_0.<AddCallbackRemoveAllCallbackTest>b__0()
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(38,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #2 (Xunit.Sdk.EqualException) -----
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(311,0): at System.Device.Gpio.Tests.GpioControllerTestBase.<>c__DisplayClass19_0.<AddCallbackRemoveAllCallbackTest>b__0()
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(38,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #3 (Xunit.Sdk.EqualException) -----
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(311,0): at System.Device.Gpio.Tests.GpioControllerTestBase.<>c__DisplayClass19_0.<AddCallbackRemoveAllCallbackTest>b__0()
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(38,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #4 (Xunit.Sdk.EqualException) -----
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(311,0): at System.Device.Gpio.Tests.GpioControllerTestBase.<>c__DisplayClass19_0.<AddCallbackRemoveAllCallbackTest>b__0()
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(38,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #5 (Xunit.Sdk.EqualException) -----
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(311,0): at System.Device.Gpio.Tests.GpioControllerTestBase.<>c__DisplayClass19_0.<AddCallbackRemoveAllCallbackTest>b__0()
        /_/src/System.Device.Gpio.Tests/RetryHelper.cs(38,0): at System.Device.Gpio.Tests.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
    System.Device.Gpio.Tests.WindowsDriverTests.AddCallbackRemoveAllCallbackTest [FINISHED] Time: 16.3164712s
    System.Device.Gpio.Tests.WindowsDriverTests.WaitForEventRisingEdgeTest [STARTING]
```

**Comment by krwq** [comment]
Duplicate of https://github.com/dotnet/iot/issues/629
