### ISSUE TITLE
Unhandled exception. Pin X does not support mode InputPullUp.

### ISSUE THREAD

**Issue by ReneElizondo** [dotnet/iot#1867]
**Describe the bug**

When running my application, I get the following error: `Unhandled exception. System.InvalidOperationException: Pin 20 does not support mode InputPullUp.`

```
Unhandled exception. System.InvalidOperationException: Pin 20 does not support mode InputPullDown.
   at System.Device.Gpio.GpioController.SetPinMode(Int32 pinNumber, PinMode mode)
   at System.Device.Gpio.GpioController.OpenPin(Int32 pinNumber, PinMode mode)
   at ..............
```

**Steps to reproduce**

```csharp
var myGpioController = new GpioController();
myGpioController.OpenPin(20, PinMode.InputPullUp);
```

**Versions used**

System.Device.Gpio 1.5.0
System.IO.Ports 5.0.1

**More Information**

I suspect that the issue has to do with the Raspberry Pi model revision, I have a couple of Raspberry Pi model `Raspberry Pi 4 Model B Rev 1.4` and everything works perfectly fine, but when running under model `Raspberry Pi 4 Model B Rev 1.5` things break. Notice that one is `Rev 1.4 `while the other is `Rev 1.5`. I am not 100% sure that is the issue but the pattern holds.

This issue appears to be similar to the one here: https://github.com/dotnet/iot/issues/1291

Below is the output of cat /proc/cpuinfo

```
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : d03115
Serial          : 10000000c39faeb6
Model           : Raspberry Pi 4 Model B Rev 1.5
```

Thank you.

**Comment by ReneElizondo** [comment]
Never mind, upgrading to the latest `System.Device.Gpio` and `System.IO.Ports` libraries fixed the problem. Should have seen that from the beginning!
