### ISSUE TITLE
Error 22 initializing the Gpio driver

### ISSUE THREAD

**Issue by nikneem** [dotnet/iot#1868]
Hi,
I have a freshly installed Raspberry Pi and installed docker on it using these instructions:
https://dev.to/elalemanyo/how-to-install-docker-and-docker-compose-on-raspberry-pi-1mo

Then I try to run a docker container that runs an ASP.NET 6 app controlling GPIO Pin 17 (Physical pin 11).
My code crashes on `controller.OpenPin(Pin, PinMode.Input);` with error `Error 22 initializing the Gpio driver`

The docker command I run is `docker run --privileged -it -d --restart unless-stopped -p 8000:80 --name fastenseatbelt nikneem/raspi-escape-fastenseatbelt:latest` and it should be easy to replicate because this images comes from a public docker registry.

I cannot find where code 22 comes from and what it means. Any help would be appreciated.

I get the following error:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMI056PIK7VG", Request id "0HMI056PIK7VG:00000002": An unhandled exception was thrown by the application.
      System.IO.IOException: Error 22 initializing the Gpio driver.
         at System.Device.Gpio.Drivers.RaspberryPi3LinuxDriver.Initialize()
         at System.Device.Gpio.Drivers.RaspberryPi3LinuxDriver.OpenPin(Int32 pinNumber)
         at System.Device.Gpio.Drivers.RaspberryPi3Driver.OpenPin(Int32 pinNumber)
         at System.Device.Gpio.GpioController.OpenPinCore(Int32 pinNumber)
         at System.Device.Gpio.GpioController.OpenPin(Int32 pinNumber)
         at System.Device.Gpio.GpioController.OpenPin(Int32 pinNumber, PinMode mode)
         at EscapeCaravan.FastenSeatbelt.Controllers.StatusLed.GetPinStatus() in /src/EscapeCaravan.FastenSeatbelt/Controllers/StatusLed.cs:line 23
         at lambda_method2(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

My code looks like so:
```csharp
using System.Device.Gpio;
using System.Device.Gpio.Drivers;
using MyProject.FastenSeatbelt.Models;
using Microsoft.AspNetCore.Mvc;

namespace MyProject.FastenSeatbelt.Controllers;

[Route("api/[controller]")]
[ApiController]
public class StatusLed : ControllerBase
{

    private const int Pin = 17; // GPIO 17 (Physical pin 11)


    [HttpGet]
    public IActionResult GetPinStatus()
    {
        Console.WriteLine($"Request status of pin {Pin}");

        var controller = new GpioController(PinNumberingScheme.Logical, new RaspberryPi3Driver() );
        
        controller.OpenPin(Pin, PinMode.Input);
        var pinStatus = controller.Read(Pin);
        controller.ClosePin(Pin);

        Console.WriteLine($"Pin status found for pin {Pin}, was {pinStatus}");
        return Ok(new PinStatus
        {
            Pin = Pin,
            Status = pinStatus.ToString()
        });
    }
}

**Comment by Ellerbach** [comment]
You should check this thread: https://github.com/dotnet/iot/issues/1467
It's about changing the driver.
