### ISSUE TITLE
PWM is not enabled on all machines

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#2052]
Some machines like `ddvsorpil019` are not able to run PWM tests while some other `ddvsorpil016` can.

Here is how it manifests:

```
    System.Device.Gpio.Tests.PwmTests.ChangingFrequency_UpdatesDutyCycle [FAIL]
      System.ArgumentException : The chip number 0 is invalid or is not enabled.
      Stack Trace:
        /_/src/System.Device.Gpio/System/Device/Pwm/Channels/UnixPwmChannel.cs(176,0): at System.Device.Pwm.Channels.UnixPwmChannel.Validate()
        /_/src/System.Device.Gpio/System/Device/Pwm/Channels/UnixPwmChannel.cs(43,0): at System.Device.Pwm.Channels.UnixPwmChannel..ctor(Int32 chip, Int32 channel, Int32 frequency, Double dutyCycle)
        /_/src/System.Device.Gpio/System/Device/Pwm/PwmChannel.cs(79,0): at System.Device.Pwm.PwmChannel.Create(Int32 chip, Int32 channel, Int32 frequency, Double dutyCyclePercentage)
        /_/src/System.Device.Gpio.Tests/SetupHelpers.cs(76,0): at System.Device.Gpio.Tests.SetupHelpers.CreatePwmChannelCore(Int32 frequency, Double dutyCycle)
        /_/src/System.Device.Gpio.Tests/SetupHelpers.cs(88,0): at System.Device.Gpio.Tests.SetupHelpers.CreatePwmChannel(Int32 frequency, Boolean stopped, Double dutyCycle)
        /_/src/System.Device.Gpio.Tests/PwmTests.cs(87,0): at System.Device.Gpio.Tests.PwmTests.ChangingFrequency_UpdatesDutyCycle()
```

@Ellerbach is testing if we can enable PWM programmatically with Board somehow.

In the meantime those tests are disabled here: https://github.com/dotnet/iot/pull/2051

https://github.com/dotnet/iot/blob/e12acc2a629e23daa6c4b3a5c15349450f6ffc6b/eng/sendToHelix.proj#L12

**Comment by krwq** [comment]
[Triage] We're working on the fix

**Comment by krwq** [comment]
[Triage] we're not seeing original issue anymore. We should still make it easy to enable PWM somehow with a script or other way but it's not urgent anymore
