### ISSUE TITLE
System.IO.IOException: Error 13 initializing the Gpio driver - RP4, Ubuntu 19.10.1

### ISSUE THREAD

**Issue by IvanFarkas** [dotnet/iot#982]
**System.IO.IOException: Error 13 initializing the Gpio driver**

Running [Simple Flashing Sample](https://darenmay.com/blog/net-core-and-gpio-on-the-raspberry-pi---leds-and-gpio/)

****dotnet run** at prompt**

```csharp
using System;
using System.Device.Gpio;
using System.Threading;
using System.Threading.Tasks;

namespace test
{
  class Program
  {
    static void Main(string[] args)
    {
      // GPIO 17 which is physical pin 11
      int ledPin1 = 17;
      GpioController controller = new GpioController();

      // Sets the pin to output mode so we can switch something on
      controller.OpenPin(ledPin1, PinMode.Output);

      int lightTimeInMilliseconds = 1000;
      int dimTimeInMilliseconds = 200;

      while(true)
      {
        Console.WriteLine($"LED1 on for {lightTimeInMilliseconds}ms");

        // turn on the LED
        controller.Write(ledPin1, PinValue.Low);
        Thread.Sleep(lightTimeInMilliseconds);
        Console.WriteLine($"LED1 off for {dimTimeInMilliseconds}ms");

        // turn off the LED
        controller.Write(ledPin1, PinValue.High);
        Thread.Sleep(dimTimeInMilliseconds);
      }
    }
  }
}
```

**Expected behavior**
Expected to work

**Actual behavior**
```
ubuntu@ubuntu:~/projects/test$ dotnet run
Unhandled exception. System.IO.IOException: Error 13 initializing the Gpio driver.
   at System.Device.Gpio.Drivers.RaspberryPi3Driver.Initialize()
   at System.Device.Gpio.Drivers.RaspberryPi3Driver.OpenPin(Int32 pinNumber)
   at System.Device.Gpio.GpioController.OpenPin(Int32 pinNumber)
   at System.Device.Gpio.GpioController.OpenPin(Int32 pinNumber, PinMode mode)
   at test.Program.Main(String[] args) in /home/ubuntu/projects/test/Program.cs:line 17
```

**Versions used**
1.0

Add following information:
- `dotnet --info` on the machine being used to build
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-arm64
 Base Path:   /home/ubuntu/.dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/home/ubuntu/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/home/ubuntu/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/home/ubuntu/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- `dotnet --info` on the machine where app is being run (not applicable for self-contained apps): **same as above**
- Version of `System.Device.Gpio` package: **1.0**
- Version of `Iot.Device.Bindings` package (not needed if bug is in `System.Device.Gpio`): **1.0**

**Comment by IvanFarkas** [comment]
# Solution
Removed ~/.dotnet directory
[Installing .NET Core on Linux ARM64](https://gist.github.com/richlander/467813274cea8abc624553ee72b28213#installing-net-core-on-linux-arm64)
Used [dotnet-docker/3.1/sdk/bionic/arm64v8/Dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/3.1/sdk/bionic/arm64v8/Dockerfile) as a base
Used ```libicu63``` instead of ```libicu60``` since I am using Ubuntu 19.10.1
## Enabled resources
```
sudo groupadd -f --system gpio
sudo groupadd -f --system i2c
sudo groupadd -f --system input
sudo groupadd -f --system spi

sudo adduser ubuntu gpio
sudo adduser ubuntu i2c
sudo adduser ubuntu input
sudo adduser ubuntu spi
```

Instead of 
```
dotnet run
```
I ran it with
```
sudo bin/Debug/netcoreapp3.1/./test
```

I observed output and blinking LED 
```
LED1 on for 1000ms
LED1 off for 200ms
LED1 on for 1000ms
LED1 off for 200ms
LED1 on for 1000ms
. . .
```
